name: "🐞 BugFix"
description: "새로운 기능 추가"
labels: ["🐞 BugFix", "Priority: Low", "Status: To Do"]
body:
  - type: textarea
    attributes:
      label: 📄 Description
      description: 버그에 대한 설명을 작성해 주세요. 발생 위치, 증상, 재현방법
      placeholder: 자세히 적을수록 좋습니다!
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🙋🏻 Reference
      description: 참고 자료가 있다면 작성해 주세요. ex) 스크린샷
