name: Backend Deploy CI/CD
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          token: '${{ secrets.SUB_TOKEN }}'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Remove previous snapshot.jar
        run: rm -rf ./build/libs/*.jar

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64 -t baekya-hackathon/baekya-backend:latest .

      - name: Tag Docker image for push
        run: docker tag baekya-hackathon/baekya-backend:latest gisu1102/baekya-hackathon:latest

      - name: Push Docker image
        run: docker push gisu1102/baekya-hackathon:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
              ssh spring-server "sudo docker ps -a"
              ssh spring-server "sudo docker rm -f baekya-backend || true"
              ssh spring-server "sudo docker pull gisu1102/baekya-hackathon:latest"
              ssh spring-server "sudo docker run -d -p 8080:8080 --name baekya-backend gisu1102/baekya-hackathon:latest"
              ssh spring-server "sudo docker images -f 'dangling=true' -q | xargs sudo docker rmi || true"
              ssh spring-server "sudo docker ps -a"
